name: Generate and Publish Docs

on:
  push:
    branches:
      - master

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false

jobs:
  generate-docs:
    # Only run the root repository
    if: startsWith(github.repository, 'spinnaker/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Docs
        run: ./gradlew dokkaHtml --stacktrace
      - name: Publish orca-api docs
        uses: spinnaker/ghaction-copy-to-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.SPINNAKER_GITHUB_TOKEN }}
        with:
          source-directory: orca-api/build/dokka/html/
          destination-github-username: spinnaker
          destination-repository-name: spinnaker.github.io
          destination-directory: reference/api/service-plugin-apis/orca-api/master/x
          user-email: sig-docs@spinnaker.io
          user-name: autodocs
